apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databaseconnections.crds.example.com
spec:
  group: crds.example.com
  scope: Namespaced
  names:
    plural: databaseconnections
    singular: databaseconnection
    kind: DatabaseConnection
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                engine:
                  type: string
                defaultSchema:
                  type: string
                rootUser:
                  type: string
                rootPassword:
                  type: string
